---
- name: Install and configure Nginx
  hosts: web
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: true

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Copy Nginx config for WordPress site with PHP support
      copy:
        dest: /etc/nginx/sites-available/wordpress
        content: |
          server {
              listen 80;
              server_name _;
              root /var/www/html;

              index index.php index.html index.htm;

              location / {
                  try_files $uri $uri/ /index.php?$args;
              }

              location ~ \.php$ {
                  include snippets/fastcgi-php.conf;
                  fastcgi_pass unix:/run/php/php8.4-fpm.sock;
              }

              location ~ /\.ht {
                  deny all;
              }
          }
      notify: Reload Nginx

    - name: Enable WordPress site config
      file:
        src: /etc/nginx/sites-available/wordpress
        dest: /etc/nginx/sites-enabled/wordpress
        state: link
        force: yes

    - name: Remove default site config if present
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: Reload Nginx

    - name: Create PHP info page for testing
      copy:
        dest: /var/www/html/phpinfo.php
        content: "<?php phpinfo(); ?>"
        owner: www-data
        group: www-data
        mode: "0644"

    - name: Ensure Nginx is started and enabled
      service:
        name: nginx
        state: started
        enabled: true

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
