---
- name: Gather EC2 instance info and create dynamic inventory
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get all running EC2 instances with tag 'Name=WordPress'
      amazon.aws.ec2_instance_info:
        region: eu-central-1 # also defined in ../terraform/provider.tf
        filters:
          "tag:Name": "WordPress"
          instance-state-name: running
      register: ec2_info

    - name: Create inventory file with proper group structure
      copy:
        dest: ./inventory_dynamic.yml
        content: |
          all:
            children:
              web:
                hosts:
          {% for instance in ec2_info.instances %}
                  {{ instance.public_ip_address }}:
                    ansible_user: ubuntu
                    ansible_ssh_private_key_file: ../terraform/mysecurekey.pem
          {% endfor %}
