---
- name: Gather EC2 instance info and create dynamic inventory
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get all running EC2 instances with tag 'Name=WordPress'
      amazon.aws.ec2_instance_info:
        region: eu-central-1
        filters:
          "tag:Name": "WordPress"
          instance-state-name: running
      register: ec2_info

    - name: Generate inventory file using template
      template:
        src: templates/inventory.j2
        dest: inventories/inventory_dynamic.yml
